

import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Orderdetails extends javax.swing.JFrame {
  Connection con;
    /**
     * Creates new form Orderdetails
     */
    public Orderdetails() {
        
        initComponents();
       String url ="jdbc:mysql://localhost/project";
    String user = "root";
    String pass="";
    
    try{
      con = java.sql.DriverManager.getConnection(url,user,pass);
    }catch(Exception ex){
        System.out.println("Error :" + ex.getMessage());
    }
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jTextField18 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jTextField19 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jTextField20 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jTextField21 = new javax.swing.JTextField();
        jButton16 = new javax.swing.JButton();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jTextField28 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton21 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Product Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 310, 40));

        jTextField1.setBackground(new java.awt.Color(0, 153, 0));
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField1.setText("Beauty & Health");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        jTextField2.setText("0");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 60, 30));

        jTextField3.setText("0");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 60, -1));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, 20));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 40, 20));

        jTextField4.setText("0");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 60, -1));

        jTextField5.setText("0");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 60, -1));

        jButton3.setBackground(new java.awt.Color(204, 0, 0));
        jButton3.setText("X");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 20));

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setText("X");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, -1, 20));

        jTextField6.setBackground(new java.awt.Color(0, 153, 0));
        jTextField6.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField6.setText("SAOP");
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 100, -1));

        jTextField7.setText("0");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 60, -1));

        jTextField8.setText("0");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 60, -1));

        jButton5.setBackground(new java.awt.Color(204, 0, 0));
        jButton5.setText("X");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, 20));

        jButton6.setBackground(new java.awt.Color(204, 0, 0));
        jButton6.setText("X");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, 20));

        jTextField9.setText("0");
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, -1));

        jTextField10.setText("0");
        getContentPane().add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 60, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Healing Soap:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        jButton7.setBackground(new java.awt.Color(204, 0, 0));
        jButton7.setText("X");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, 20));

        jButton8.setBackground(new java.awt.Color(204, 0, 0));
        jButton8.setText("X");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, 20));

        jTextField11.setBackground(new java.awt.Color(0, 153, 0));
        jTextField11.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField11.setText("Coffee & Tea");
        getContentPane().add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 130, -1));

        jTextField12.setText("0");
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 60, -1));

        jButton9.setBackground(new java.awt.Color(204, 0, 0));
        jButton9.setText("X");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 40, 20));

        jTextField13.setText("0");
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 60, -1));

        jTextField14.setText("0");
        getContentPane().add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 60, -1));

        jButton10.setBackground(new java.awt.Color(204, 0, 0));
        jButton10.setText("X");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, 20));

        jButton11.setBackground(new java.awt.Color(204, 0, 0));
        jButton11.setText("X");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, 20));

        jTextField15.setBackground(new java.awt.Color(0, 153, 0));
        jTextField15.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField15.setText("Oil & Tonics(Orally)");
        getContentPane().add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 150, -1));

        jTextField16.setBackground(new java.awt.Color(0, 153, 0));
        jTextField16.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField16.setText("Fitness");
        getContentPane().add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 110, -1));

        jTextField17.setText("0");
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 60, -1));

        jButton12.setBackground(new java.awt.Color(204, 0, 0));
        jButton12.setText("X");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 290, -1, 20));

        jTextField18.setText("0");
        getContentPane().add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 60, -1));

        jButton13.setBackground(new java.awt.Color(204, 0, 0));
        jButton13.setText("X");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, 20));

        jTextField19.setText("0");
        getContentPane().add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 60, -1));

        jButton14.setBackground(new java.awt.Color(204, 0, 0));
        jButton14.setText("X");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, -1, 20));

        jTextField20.setText("0");
        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 60, -1));

        jButton15.setBackground(new java.awt.Color(204, 0, 0));
        jButton15.setText("X");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, 20));

        jTextField21.setText("0");
        getContentPane().add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, 60, -1));

        jButton16.setBackground(new java.awt.Color(204, 0, 0));
        jButton16.setText("X");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, 20));

        jTextField22.setText("0");
        jTextField22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField22ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 60, -1));

        jTextField23.setText("0");
        jTextField23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField23ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, 60, -1));

        jButton17.setBackground(new java.awt.Color(204, 0, 0));
        jButton17.setText("X");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, -1, 20));

        jTextField24.setBackground(new java.awt.Color(0, 153, 0));
        jTextField24.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        jTextField24.setText("Order Info");
        getContentPane().add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 120, -1));

        jTextField25.setText("23A");
        getContentPane().add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 120, -1));

        jTextField26.setText("6 November 2023");
        getContentPane().add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 120, -1));

        jTextField27.setText("Backorder");
        getContentPane().add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 120, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Grand Total:");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, -1, -1));

        jButton19.setText("View product Details");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, -1));

        jButton20.setBackground(new java.awt.Color(0, 153, 0));
        jButton20.setText(">");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));
        getContentPane().add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 120, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Order Type:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, -1, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel26.setText("Order Date:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, -1));

        jButton21.setText("ADD Products");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 63, -1, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("OrderNo:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, -1, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setText("Amount:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, 20));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel24.setText("Amount:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Organic SuperFood :");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Marvellous Man:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Lip Balm:");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Sport Message Oil:");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Hemorroid cream:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Nerve Tonic:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("CBD OIL:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Coffee Beans:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jButton18.setBackground(new java.awt.Color(204, 0, 0));
        jButton18.setText("X");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, 20));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Achillea Tea Bags:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Coffee Pods:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Circulation Soap:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Anti-Fungal:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Acne Soap:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Facial Toner:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Sambok Balsam:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 180, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Hair Oil:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 150, 50, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Face Mask:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 120, 70, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 560, 570));

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        ManageProduct cs = new ManageProduct();
      cs.setVisible(true);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jTextField22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField22ActionPerformed

    private void jTextField23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField23ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
     
        
        String sql = "SELECT * FROM beauty";
     try{
        java.sql.PreparedStatement pst = con.prepareStatement(sql);
        ResultSet rs = pst.executeQuery();
       
        if(rs.next()){
         jTextField2.setText(rs.getString(2));
         jTextField3.setText(rs.getString(3));
         jTextField4.setText(rs.getString(4));
         jTextField5.setText(rs.getString(5));
        }
     }catch(Exception ex)  {
         System.out.println("Error :" +ex.getMessage());
     } 
       String sql1 = "SELECT * FROM soap";
     try{
        java.sql.PreparedStatement pst = con.prepareStatement(sql1);
        ResultSet rs = pst.executeQuery();
      
        if(rs.next()){
         jTextField7.setText(rs.getString(2));
         jTextField8.setText(rs.getString(3));
         jTextField9.setText(rs.getString(4));
         jTextField10.setText(rs.getString(5));
        }
     }catch(Exception ex)  {
         System.out.println("Error :" +ex.getMessage());
     } 
      String sql2 = "SELECT * FROM coffee";
     try{
        java.sql.PreparedStatement pst = con.prepareStatement(sql2);
        ResultSet rs = pst.executeQuery();
      
        if(rs.next()){
         jTextField12.setText(rs.getString(2));
         jTextField13.setText(rs.getString(3));
         jTextField14.setText(rs.getString(4));
        
        }
     }catch(Exception ex)  {
         System.out.println("Error :" +ex.getMessage());
     } 
      String sql3 = "SELECT * FROM oil2";
     try{
        java.sql.PreparedStatement pst = con.prepareStatement(sql3);
        ResultSet rs = pst.executeQuery();
      
        if(rs.next()){
         jTextField17.setText(rs.getString(2));
         jTextField18.setText(rs.getString(3));
         jTextField19.setText(rs.getString(4));
         
        }
     }catch(Exception ex)  {
         System.out.println("Error :" +ex.getMessage());
     } 
      String sql4 = "SELECT * FROM fitness";
     try{
        java.sql.PreparedStatement pst = con.prepareStatement(sql4);
        ResultSet rs = pst.executeQuery();
       
        if(rs.next()){
         jTextField20.setText(rs.getString(2));
         jTextField21.setText(rs.getString(3));
         jTextField22.setText(rs.getString(4));
         jTextField23.setText(rs.getString(5));
        }
     }catch(Exception ex)  {
         System.out.println("Error :" +ex.getMessage());
     } 
     double sum =Double.parseDouble(jTextField10.getText()) +Double.parseDouble(jTextField2.getText()) +Double.parseDouble(jTextField3.getText()) 
             + Double.parseDouble(jTextField4.getText()) + Double.parseDouble(jTextField5.getText()) +
             + Double.parseDouble(jTextField7.getText()) + Double.parseDouble(jTextField8.getText()) + Double.parseDouble(jTextField9.getText())
           + Double.parseDouble(jTextField12.getText()) + Double.parseDouble(jTextField13.getText()) + Double.parseDouble(jTextField14.getText())
           + Double.parseDouble(jTextField17.getText()) + Double.parseDouble(jTextField18.getText()) + Double.parseDouble(jTextField19.getText())
             + Double.parseDouble(jTextField20.getText()) + Double.parseDouble(jTextField21.getText()) + Double.parseDouble(jTextField22.getText())
             + Double.parseDouble(jTextField23.getText()) ;
    jTextField28.setText(Double.toString(sum));
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
         int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
    if(response==JOptionPane.YES_OPTION){     

      jTextField2.setText("0");
    
      
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
      
        }else{
          jLabel11.setText("");
          String FC =jTextField2.getText();
      
     
         
        
              java.sql.PreparedStatement pst = con.prepareStatement("Update beauty set FaceMask=? where id=?");
         
       Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost/project","root","");
      pst.setString(1,FC); 
    }
      }catch (Exception ex){
          Logger.getLogger(Orderdetails.class.getName()).log(Level.SEVERE, null,ex);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "update from beauty where Hairoil=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField3.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from beauty where Sambok=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField4.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from beauty where Facial=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField5.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "replace from soap where Asoap=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField7.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "replace from soap where Afungal=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField8.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from soap where Csoap=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField9.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from soap where Hsoap=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField10.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
     int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from coffee where Pods=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField12.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from coffee where Achillea=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField13.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from coffee where Beans=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField14.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
    int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from oil2 where CBDoil=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField17.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from oil2 where Nervetonic=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField18.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from oil2 where Hcream=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField19.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
   int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from fitness where sportmassage=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField20.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from fitness where lipbalm=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField21.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
     int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from fitness where Marvellousman=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField22.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
    int response = JOptionPane.showConfirmDialog(this, "Are you certain you want to cancel this item","Remove item",JOptionPane.YES_NO_OPTION);
        String sql = "delete from fitness where Wheatgrass=?";
    if(response==JOptionPane.YES_OPTION){     
try{
     java.sql.PreparedStatement pst = con.prepareStatement(sql);
     pst.setString(1, jTextField23.getText());
       pst.execute();
          JOptionPane.showMessageDialog(null, "Item Removed Successfully");
    
}catch(Exception e){
    JOptionPane.showMessageDialog(null, e);
}
 }else if(response==JOptionPane.NO_OPTION){
            jLabel11.setText("");
        }
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        Ourproducts or = new Ourproducts();
     or.setVisible(true);
    }//GEN-LAST:event_jButton21ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Orderdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Orderdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Orderdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Orderdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Orderdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
